package com.hms.pharmacy.entity;

public enum Category {
    ANALGESIC,
    ANTIBIOTIC,
    ANTIINFLAMMATORY,
    ANTIALERGIC,
    ANTIVIRAL,
    ANTIFUNGAL,
    ANTIPYRETIC,
    ANTIHYPERTENSIVE,
    ANTIDIABETIC,
    ANTIDEPRESSANT,
    ANTIANXIETY,
    ANTICONVULSANT,
    HORMONAL,
    VACCINE,
    SUPPLEMENT,
    ANESTHETIC,
    GASTROINTESTINAL,
    CARDIOVASCULAR,
    RESPIRATORY,
    DERMATOLOGICAL
}
