spring.application.name=AppointmentsMS
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/appointmentsdb
spring.datasource.username=root
spring.datasource.password=@nicolas2018
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.config.import=optional:file:.env
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

APPOINTMENT_NOT_FOUND=Patient not found
APPOINTMENT_ALREADY_CANCELLED = Appointment already cancelled
APPOINTMENT_ALREADY_COMPLETED = Appointment already completed
DOCTOR_NOT_FOUND = Doctor not found
PATIENT_NOT_FOUND = Patient not found
APPOINTMENT_RECORD_ALREADY_EXISTS = Appointment record already exists
APPOINTMENT_RECORD_NOT_FOUND = Appointment record not found
PRESCRIPTION_NOT_FOUND = Prescription not found