spring.application.name=PharmacyMS

server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacydb
spring.datasource.username=root
spring.datasource.password=@nicolas2018
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.config.import=optional:file:.env

MEDICINE_ALREADY_EXISTS = Medicine Already Exists
MEDICINE_NOT_FOUND = Medicine not found
INVENTORY_NOT_FOUND = Medicine Inventory not found
STOCK_NOT_FOUND = Medicine stock not found
SALE_ALREADY_EXISTS = "Sale already exists"
SALE_NOT_FOUND = "Sale not found"
INSUFFICIENT_STOCK = "A medicine in the sale has insufficient stock"